### ISSUE TITLE
Change when a training event is removed from the website

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#103]
**Is your feature / client request related to a problem? Please describe.**
At the moment a training event automatically comes off the website on the day of the training, this means that people can't see the event to buy tickets on the day of the event.

**Describe the solution you'd like**
Would it be possible to change it so that the events are removed the day after the event or at midnight on the evening of the event please? https://www.chilternmusictherapy.co.uk/training

**Describe alternatives you've considered**

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
Thanks for flagging @katieshuster. We will look into this after the other prioritised issues are complete!

**Comment by fadeomar** [comment]
hey @katieshuster , this is done! the events will be removed the day after the event day

**Comment by katieshuster** [comment]
Thanks @fadeomar - @ihall78 something to test when you're back from leave

**Comment by ihall78** [comment]
Thanks. I can test this on Thursday as we have a training then.

**Comment by ihall78** [comment]
@fadeomar @cyberteenie I've just noticed that tomorrow evening's training (Gender Awareness in Music Therapy at 6pm) has now disappeared from the website - can you please reinstate it asap as tickets are still on sale until 2pm tomorrow? We need our training events to stay on the website until the day after the event or at midnight on the evening of the event. Thanks

**Comment by cyberteenie** [comment]
@ihall78 - absolutely. I will let the team know!

**Comment by ihall78** [comment]
We've actually just cancelled tonight's training and stopped ticket sales so we don't need it to back up on the website but I want to ensure the same thing doesn't happen with the next training (which is on Tuesday). Could you please check that? Thanks

**Comment by cyberteenie** [comment]
Ok good to know. We will look into it!

**Comment by ihall78** [comment]
@fadeomar We need the event to come off the website when the sales end. Is there a way to do this? We have an Eventbrite integration and the time that sales close is on Eventbrite. If not, can we have it so that it comes off the website either when the training starts (e.g. 6pm on 20th April on that Gender Awareness training) or the end of that day if not? Thanks

**Comment by fadeomar** [comment]
hey @ihall78 there are two ways to implement this request to turning off the event manually :

   1- whenever you want to change the state of the event from live to not  live, you can save the event as draft and  that will change  the state of that event to become not live but you will still have that event ant it's data in the collection list and you have the ability to to update the data and publish it again whenever you want 
![image](https://user-images.githubusercontent.com/39485495/235345419-f5314961-2480-48f3-bdfd-1e41779bbf29.png)

   
   2- the second way, it's actually the same approach but adding anther field  to the CMS for example we can call it (turn off) and it will be a switch input and then add filter to the data coming form the CMS to not show any event that turn off input is ON then whenever you want to change the state of event from live to not live just make the turn off input ON and then the event will become  not live but you will still have that event ant it's data in the collection list and you have the ability to to update the data and publish it again whenever you want 
   
   the two methods are working the same, you will  have the ability to change the state of the event between live and not live manually at any time, 
   the first method not require a development because it's a feature built in Webflow itself (look to image attached above ) but the second one will require development form our side, let me know if it make since and what method you will use ?

**Comment by fadeomar** [comment]
hey @ihall78 there is a functionality to filter the event when the date is expired after one day as requested and you don't have to change the state to be draft in this case, but in case you want to hide any event manually for any reason, for example, the sales end you have the ability to do that manually by changing the state to draft, hope that makes sense please let me know you if not and maybe we can arrange a call if needed :)

**Comment by cyberteenie** [comment]
Hi @ihall78 - I just wanted to check in if that works for you and if we can close this issue?

**Comment by ihall78** [comment]
Yes, please close the case. Thanks
