### ISSUE TITLE
Apply now button not working

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#114]
**Is your feature / client request related to a problem? Please describe.**
The 'apply now' button on this page is not working: https://www.chilternmusictherapy.co.uk/job-volunteering/external-hr-and-compliance-director - it should open a page for people to send an email to recruitment@chilternmusictherapy.co.uk

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
Hi @katieshuster - when I test this it works for me. Can you provide a bit more information about what happens for you?

**Comment by katieshuster** [comment]
Hi @cyberteenie we actually had an email from someone who said they tried to click on it and it didn't work and they tried on numerous browsers. When I click on it, it just opens and untitled page. I have recorded a loom: https://www.loom.com/share/398393085ea540729195ad4373bb9b36?sid=7c38f44a-0e6d-4411-acd0-d0c2098f8b75

**Comment by bethanyios** [comment]
Hi @katieshuster the apply now button opens an email window on my computer. It may be that yours isn't set up to allow this. @fadeomar when you are able to look into this we need to think about another way to submit an application because this may happen for a few people. 

cc. @thejoefriel maybe we should link to a page instead with a form or integrate Workable?

**Comment by cyberteenie** [comment]
@katieshuster, yes this definitely looks like your browser is blocking this. How do you feel about linking it to some sort of contact form instead?

**Comment by cyberteenie** [comment]
Ok! Will discuss with @fadeomar

**Comment by cyberteenie** [comment]
@katieshuster after speaking with Fadi and testing this on many devices, it does seem that the button is working but may be blocked on certain devices due to the device configuration. I think that the leanest way to approach this would actually be replacing the button with a link to the email address itself, so that people could create an email and send it directly to recruitment.

What do you think?

We spoke about some other possible solutions, but there are tons of little restrictions and limitations...adding an email might actually solve the issue in the cleanest way.

**Comment by katieshuster** [comment]
Hi @cyberteenie I think lets try that and see how it goes?

**Comment by cyberteenie** [comment]
Ok great, I will let @fadeomar know!

**Comment by fadeomar** [comment]
hey, @katieshuster @cyberteenie I've updated the change at it's ready now :)

**Comment by cyberteenie** [comment]
@katieshuster feel free to test if you are happy with it!

**Comment by katieshuster** [comment]
Hey @fadeomar it looks good, my only concern is that on my screen, the purple box goes over the footer? Is it possible to remove extra space please? 
![image](https://github.com/yalla-coop/chiltern-website/assets/89024047/dd8f48a4-75e9-4111-99b7-e498ff16e114)

**Comment by fadeomar** [comment]
hey @katieshuster can you provide a link for this page, please

**Comment by cyberteenie** [comment]
Hey @fadeomar - it is happening on all of the dynamic job opportunity pages. For instance:
https://www.chilternmusictherapy.co.uk/job-volunteering/neurologic-music-therapist-stoke-on-trent-and-burton-upon-trent

https://www.chilternmusictherapy.co.uk/job-volunteering/freelance-music-therapists

Thanks!

**Comment by fadeomar** [comment]
hey @cyberteenie @katieshuster this is fix now

**Comment by katieshuster** [comment]
Thanks @fadeomar
