### ISSUE TITLE
Remove iPod Pharmacy from website

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#73]
**Is your feature / client request related to a problem? Please describe.**
We are no longer running the iPod Pharmacy so we would like to remove this from the website

**Describe the solution you'd like**
To remove the iPod Pharmacy box from this page: https://www.chilternmusictherapy.co.uk/support-us
![Screenshot 2022-06-28 091922](https://user-images.githubusercontent.com/89024047/176130351-fb36f16a-331b-450a-929d-56484b4985ac.png)

**Describe alternatives you've considered**
N/A

**Additional context**
If this is something that I can do myself, please let me know

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by yalla-coop-sla** [comment]
Hi Katie, let me speak to the dev team and see if this is something you can do from your end and get back to you. Thanks!

**Comment by fadeomar** [comment]
hey @katieshuster I've removed the section and for your question, yes you can do that your self but it's too risky because it's static element not CMS content, It may cause side problems in the style

**Comment by cyberteenie** [comment]
@katieshuster - feel free to check that this is working from you end and close this issue!
After speaking to the development team, they warned me that moving forward, it is better for you to open issues on Github so that they can complete changes on their end. There is no history on Webflow, so if something goes wrong when you try to change it, it may take longer for them to have to fix it. Do let me know if you have any questions about this! Thanks!

**Comment by katieshuster** [comment]
Hi @fadeomar sorry I can still see part of the box on the support us page. Are you able to remove it completely please?
![Screenshot 2022-07-13 102420](https://user-images.githubusercontent.com/89024047/178700028-95b171f6-1d78-4419-a173-663e899ac833.png)

**Comment by fadeomar** [comment]
hey @katieshuster it's ready for test again

**Comment by katieshuster** [comment]
Thanks @fadeomar that's great
