### ISSUE TITLE
Move events tab

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#76]
**Is your feature / client request related to a problem? Please describe.**
It's not a problem but I think from a user perspective it doesn't really work.

**Describe the solution you'd like**
I would like to move the events tab from here: https://www.chilternmusictherapy.co.uk/insights to here is possible please: https://www.chilternmusictherapy.co.uk/get-involved as I think events are for people to get involved and not an insight

**Describe alternatives you've considered**
If 4 tabs on the get involved page is too many then we could potentially combine the job and volunteer opportunities tab into one and then there would be:
- training
- Job/Volunteer Opportunities
- Events

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
Thanks @katieshuster . I will pass this off to the development team!

**Comment by fadeomar** [comment]
hey @katieshuster I want to confirm the changes from you before start working on this because it can't be undone 
here is what I get from the issue 

1- remove events tap from insights page https://www.chilternmusictherapy.co.uk/insights
2- add events tap to get involved page https://www.chilternmusictherapy.co.uk/get-involved
3- combine the job and volunteer opportunities tab into one tap 

are you agree?

**Comment by katieshuster** [comment]
Hi @fadeomar yes that sounds great thank you. Can the order of the tabs be:
1. Training
2. Careers (job and volunteers combined)
3. Events

**Comment by fadeomar** [comment]
hey @katieshuster this is done and can be tested

**Comment by katieshuster** [comment]
That looks great thank you.
