### ISSUE TITLE
Add research article in Who we work pages if a story doesn't exist

### ISSUE THREAD

**Issue by jema28** [yalla-coop/chiltern-website#79]
__Related issue(s)__
#78 

- [x] @fadeomar to outline a possible solution/estimated amount of time and let me and Katie know

### User Acceptance Criteria:

- [x] Add research articles in Who we work pages if a story doesn't exist. Example page including story: https://www.chilternmusictherapy.co.uk/insights-tags/brain-injury-neuro-disability. 

cc @cyberteenie

**Comment by cyberteenie** [comment]
Great! Thank you!

**Comment by fadeomar** [comment]
hey @jema28 the estimation time on this is 2~2.5 hr

**Comment by jema28** [comment]
Total time estimation for this issue and #80 in terms of design/admin/testing is 4 hours. 

@fadeomar can you add your estimation in the issue #80 also? Thanks!

cc @cyberteenie

**Comment by fadeomar** [comment]
hey @katieshuster I've done this issue, 
for the story that shown in  "Who we work with" pages you have to add tag for it because its needed to match between the story and the tag page (which one of "Who we work with" pages ) to be shown on. and if the tag wasn't selected at any of the stories then there is no story to show in the tag page. 
![image](https://user-images.githubusercontent.com/39485495/193571627-4cda73df-52e5-43a3-98d6-1bea23d34868.png)

I've done the same logic for the researches, now you have to add tags in the research items to match the tags pages that  you want the search to be appear with BUT I've added condition here only when there is no story at the same Tag page

**Comment by cyberteenie** [comment]
@katieshuster - does this solution work for you? If so feel free to close! Thanks!
