### ISSUE TITLE
Ability to add additional text and download report buttons in research articles

### ISSUE THREAD

**Issue by jema28** [yalla-coop/chiltern-website#80]
__Related issue(s)__
#78 

- [x] @fadeomar to outline a possible solution/estimated amount of time and let me and Katie know

### User Acceptance Criteria:

- [x] Ability to add additional text and download report buttons in research article pages e.g. another Special school in X section in this page https://www.chilternmusictherapy.co.uk/insights-researchs/special-schools-impact

cc @cyberteenie

**Comment by cyberteenie** [comment]
Thanks Jem!

**Comment by jema28** [comment]
Hi @katieshuster, Fadi and I have discussed this and we can do this if we have a max number of sections, for example 3. We can add this in the CMS i.e. description 1 and link 1, description 2 and link 2 and description 3 and link 3. We would then add a condition to show the items when it has content. 

Let us know if that works for you? Do you know how many max sections you would need?

**Comment by katieshuster** [comment]
Hi @jema28 that works for me. We think 3 sections should be enough. Could we make it so that it has photo 1, description 1 and link 1 please. As we may want to add photos for each section.

**Comment by cyberteenie** [comment]
Thanks for letting us know @katieshuster - we will let you know if we have any other questions!

**Comment by fadeomar** [comment]
Development estimation: <0.5 days

**Comment by fadeomar** [comment]
hey @katieshuster I've done this issue sorry for delay, now you have description 1, link 1, description 2, link 2, description 3 and link 3, and you can add photos to the description fields as previous because it's reach text field and you can add photos inside and there is no need for new fields for photos because it might require a new design to know where to put the new images how it will look like but I think the current solution will match what you need as I understand I've test to add three sections with  links and here how it looks 
![image](https://user-images.githubusercontent.com/39485495/193562565-6532f151-a0d3-448d-aba6-1d704ce33b8c.png)
if you happy with the solution feel free to close the issue
