### ISSUE TITLE
Workshops

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#94]
**Is your feature / client request related to a problem? Please describe.**
When you click on the workshop tab we have noticed a couple of things that we would like changing

**Describe the solution you'd like**
1. when we click on the workshop tab we would like to be able to see the date and time on the workshops added like you can on the 'training's tab. 
![Screenshot 2023-01-27 114309](https://user-images.githubusercontent.com/89024047/215078558-497bd161-45aa-427c-b483-75a1001e8d0f.png)
![image](https://user-images.githubusercontent.com/89024047/215078719-a5751a3a-c325-41de-a2fe-5006016e47a2.png)

2. We would like the blue box on the workshop event page to be a fixed height like it is on a training event page: 
![Screenshot 2023-01-27 114135](https://user-images.githubusercontent.com/89024047/215078859-a4f73720-f254-4f21-a7eb-a6448673b0e1.png)

3. When you click into a workshop it comes up with chiltern-music-therapy-website as the page name, please can it be changed to Chiltern Music Therapy like it is on other pages? 
![image](https://user-images.githubusercontent.com/89024047/215079091-7e56d3a6-f154-4e7a-8dec-3ac332626cdb.png)

**Describe alternatives you've considered**

**Additional context**

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by cyberteenie** [comment]
@katieshuster - I will pass that off to the development team!

**Comment by fadeomar** [comment]
hey @katieshuster all fixed and ready for test 
cc @cyberteenie

**Comment by katieshuster** [comment]
Hi there, sorry we have noticed a couple of issues: the date on workshops is in American format MM/DD/YY, please can it be in UK format DD/MM/YY.

In addition, the URL refers back to where the page used to sit - is it possible to change this so instead of it saying insights-events it says 'training-events' https://www.chilternmusictherapy.co.uk/**insights-events**/introduction-to-music-therapy-workshop
thank you!

**Comment by fadeomar** [comment]
hey @katieshuster I've fixed the date formatting issue and it's ready for testing, 
but for the URL issue, it can't be changed from` /insights-events/` to `/training-events` because we already have a collection list for training and has the same URL 
![image](https://user-images.githubusercontent.com/39485495/216812836-8ea02ff5-a12b-4aef-ab25-f714d389c7f7.png)

so each item in the Training tab has URL '/trainging-events/...` because it comes from the Training events collection list 
and  for Workshops tabe has URL `insights-events/...` because it comes from the insights events collection list 
it's possible to change  `insights-events/...`  to something else Except for reserved urls for other collection 
I would suggest changing the URL form `/insights-events` to `/workshops` as the name of the tab, what do you think?

**Comment by katieshuster** [comment]
Hi Fadi, that's great thank you - yes please if it can be changed to /workshops that would be great.

Also the back button isn't going to right place, please can this be fixed.

![image](https://user-images.githubusercontent.com/89024047/216951789-0637bcba-f8b5-44fb-8efc-9caa6520c0bf.png)


Thanks

Katie

**Comment by cyberteenie** [comment]
@katieshuster I have followed up with  @fadeomar on this. He will work on it shortly! Thanks

**Comment by fadeomar** [comment]
hey @katieshuster I've modified the URL and fixed the back functionality, and this issue ready for testing

**Comment by katieshuster** [comment]
thanks @fadeomar!
