### ISSUE TITLE
Map of services

### ISSUE THREAD

**Issue by katieshuster** [yalla-coop/chiltern-website#99]
**Please select the priority level by adding one of the following labels to this issue**
- Priority-1 (Critical e.g. the website is down, multiple users unable to log into platform)
- Priority-2 (Important e.g. Staff cannot access correct information or data / Users cannot add a spend activity)
- Priority-3 (Normal e.g. Text is missing / duplicate values being shown)
- Priority-4 (Low e.g. Content is not perfectly aligned)

**Describe the bug**
The map is not correctly showing the number of staff/groups in some locations. 

**To Reproduce**
If you go to the map and click on Standlake you should see that there is 1 music therapist there
![image](https://user-images.githubusercontent.com/89024047/216629022-f6930ea9-8294-4a2e-be05-103642887ae0.png)

**Expected behavior**
You should see that there is one music therapist in Standlake as there is a tag for that:
![image](https://user-images.githubusercontent.com/89024047/216628849-09895f03-84f7-4baf-aaf5-1850497e8f56.png)

**Screenshots**

**Desktop (please complete the following information):**
Windows Google Chrome

**Smartphone (please complete the following information):**

**Additional context**
I think this may be a problem for other areas but I haven't tested all the locations

**Team - do not edit**
@thejoefriel
@fadeomar
@@Israa91

**Comment by fadeomar** [comment]
hey @katieshuster I've investigated the issue but not sure what is the bug because the custom code works fine, but I've noticed that you have listed  a long list of cities in one item in the CMS and tried to keep just 5 cities but the item at it works and fixed the issue, so here is the way to avoid this case from happening again is whenever you notice that the items in the city are more than 5 items you should stop adding a city to that item and duplicate the item to add the new cities to it so the image above will represent now in two items with the same data but with different cities 
**SO**
![image](https://user-images.githubusercontent.com/39485495/216816098-74078609-9387-41c2-be3d-f3a2549cae39.png)

**will become**
1- 
![image](https://user-images.githubusercontent.com/39485495/216816114-123cab24-c371-434f-a1aa-040607021f83.png)
2- 
![image](https://user-images.githubusercontent.com/39485495/216816126-326cbdc5-adbc-4053-83fc-88e7f246a757.png)

I hope that I make it clear as possible and it's ready for testing

**Comment by katieshuster** [comment]
Hi Fade, this makes sense, however I have just tested it and this seems to be appearing on the page? https://www.loom.com/share/15ed9d98a3d64f38b4a30f7bfe42ef0a

**Comment by katieshuster** [comment]
Is it possible to remove this white space underneath the map?
![image](https://user-images.githubusercontent.com/89024047/217006331-fe97055e-6fea-4a0e-821a-cdccadb4f2ea.png)

**Comment by fadeomar** [comment]
hey @katieshuster I was checking this issue, but it seem to be fixed, please check https://www.loom.com/share/be1e0bb307c8430aa062988e156dae51 
and let me if it happened again

**Comment by katieshuster** [comment]
Hi @fadeomar I have done a hard refresh and deleted the cache and I still have the white space I'm afraid https://www.loom.com/share/140c2e8682d44405845bbd5d202f66b7

**Comment by fadeomar** [comment]
hey @katieshuster I've invistgate the issue again and fix it, you can test again :+1:

**Comment by katieshuster** [comment]
Thanks @fadeomar that's good now!
